#!/bin/bash
C_BLACK   ="\e[30m"
C_RED     ="\e[31m"
C_GREEN   ="\e[32m"
C_YELLOW  ="\e[33m"
C_BLUE    ="\e[34m"
C_MAGENTA ="\e[35m"
C_CYAN    ="\e[36m"
C_LGRAY   ="\e[37m"
C_GRAY    ="\e[90m"
C_LRED    ="\e[91m"
C_LGREEN  ="\e[92m"
C_LYELLOW ="\e[93m"
C_LBLUE   ="\e[94m"
C_LMAGENTA="\e[95m"
C_LCYAN   ="\e[96m"
C_WHITE   ="\e[97m"
C_END     ="\e[0m"
